<!doctype html>
<html class="no-js" lang="en" dir="ltr">

<head>
    <?php include_once 'predlosci/head.phtml' ?>
</head>

<body>
    <?php include_once 'predlosci/izbornik.phtml' ?>

    <div class="grid-container">
        <div class="grid-x grid-padding-x">
            <div class="large-12 cell">
                <div class="callout" id='program'>
                    <?= $sadrzaj ?>
                </div>
            </div>
        </div>
    </div>

    <?php include_once 'predlosci/javascript.phtml' ?>
</body>

</html>