<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title"><?= App::config('naslovApp') ?></div>
</div>

<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><?= App::config('naslovApp') ?></li>
      <li><a href="<?= App::config('url') ?>">Početna</a></li>
      <li class="has-submenu">
        <a href="#0">Vjezbanje</a>
        <ul class="submenu menu vertical" data-submenu>
          <li><a href="<?= App::config('url') ?>vjezba/primjer1">Primjer1</a></li>
          <li><a href="<?= App::config('url') ?>vjezba/primjer2">Primjer2</a></li>
          <li><a href="<?= App::config('url') ?>vjezba/primjer3">Primjer3</a></li>
        </ul>
      </li>
      <li><a href="#0">Three</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><a href="<?= App::config('url') ?>login/index">Login</a></li>
    </ul>
  </div>
</div>