<form action="<?=App::config('url')?>polaznik/akcija" method="post">

    <fieldset>
        <legend>Detalji polaznika</legend>

        <label>
            Ime
            <input type="text" name="ime" value="<?=$polaznik->ime?>" />
        </label>

        <!-- ispravnije -->
        <label for="prezime">Prezime</label>
        <input type="text" name="prezime" id="prezime" 
         value="<?=$polaznik->prezime?>">

        <label for="email">Email</label>
        <input type="email" name="email" id="email" value="<?=$polaznik->email?>">

        <label for="oib">OIB</label>
        <input type="text" name="oib" id="oib" value="<?=$polaznik->oib?>">

        <label for="brojugovora">Broj ugovora</label>
        <input type="text" name="brojugovora" id="brojugovora" value="<?=$polaznik->brojugovora?>">

        <input type="hidden" name="sifra" value="<?=$polaznik->sifra?>">

        <div class="grid-x grid-padding-x">
            <div class="large-4 cell">
                <a  class="alert button expanded" 
                href="<?=App::config('url')?>polaznik/index">Odustani</a>
            </div>
            <div class="large-8 cell">
                <input type="submit" class="success button expanded" value="<?=$akcija?>">
            </div>
        </div>
        <?=$poruka?>

    </fieldset>
</form> 