<form action="<?=App::config('url')?>polaznik/index" method="get">
    <input type="text" name="uvjet" id="uvjet" placeholder="Unesite dio imena, prezimena ili OIB-a" value="<?=$uvjet?>">
    <input type="submit" class="expanded info button" value="Traži">
</form>
<nav aria-label="Pagination">
  <ul class="pagination text-center">

    <?php if($stranica-1 == 0):?>
        <li class="pagination-previous disabled">Početak</li>
        <li class="pagination-previous disabled">Prethodna</li>
    <?php else:?>
        <li class="pagination-previous "><a href="<?=App::config('url')?>polaznik/index?uvjet=<?=$uvjet?>&stranica=1" aria-label="Start page" title="Povratak na prvu stranicu">Početak</a></li>
        <li class="pagination-previous "><a href="<?=App::config('url')?>polaznik/index?uvjet=<?=$uvjet?>&stranica=<?=$stranica-1?>" aria-label="Previous page" title="Prethodna stranica">Prethodna</a></li>
    <?php endif;?>
    
    <li class="current"><span class="show-for-sr">Vi ste na stranici</span> <?=$stranica?>/<?=$ukupnoStranica?></li>
    <!-- <li><a href="#" aria-label="Page 2">2</a></li>
    <li><a href="#" aria-label="Page 3">3</a></li>
    <li><a href="#" aria-label="Page 4">4</a></li>
    <li class="ellipsis"></li>
    <li><a href="#" aria-label="Page 12">12</a></li>
    <li><a href="#" aria-label="Page 13">13</a></li> -->

    <?php if($stranica == $ukupnoStranica):?>
        <li class="pagination-next disabled">Sljedeća</li>
        <li class="pagination-next disabled">Kraj</li>
    <?php else:?>
        <li class="pagination-next"><a href="<?=App::config('url')?>polaznik/index?uvjet=<?=$uvjet?>&stranica=<?=$stranica+1?>" aria-label="Next page" title="Sljedeća stranica">Sljedeća</a></li>
        <li class="pagination-next "><a href="<?=App::config('url')?>polaznik/index?uvjet=<?=$uvjet?>&stranica=<?=$ukupnoStranica?>" aria-label="Final page" title="Idi na zadnju stranicu">Kraj</a></li>
    <?php endif;?>

  </ul>
</nav>
<div class="grid-x grid-padding-x">
    <?php include 'dodajNovi.phtml';?>
    <?php foreach($polaznici as $polaznik): ?>
        <div class="large-3 medium-4 cell">
            <div class="callout"  style="text-align: center; min-height: 220px;">
            <h1 style="font-size: 1.5rem;">
            <?=$polaznik->ime?> <?=$polaznik->prezime?></h1>
            <hr />
            <?=$polaznik->email?>
            <hr />
            <a href="<?=App::config('url')?>polaznik/detalji/<?=$polaznik->sifra?>">
                    <i title="Promjeni" 
                        class="fas fa-2x fa-edit"></i>
                </a>   
                <?php if($polaznik->grupa==0): ?>
                    <a onclick="return confirm('Sigurno obrisati?');" style="margin-left: 20px;" href="<?=App::config('url')?>polaznik/brisanje/<?=$polaznik->sifra?>">
                        <i style="color: red" title="Obriši " 
                            class="fas fa-2x fa-trash"></i>
                    </a>  
                <?php else:?>
                    <i style="margin-left: 20px;color: gray" 
                    title="Ne može se obrisati jer je clan grupe" 
                            class="fas fa-2x fa-trash"></i>
                <?php endif;?>
            </div>

        </div>
    <?php endforeach;?>
    <?php include 'dodajNovi.phtml';?>
</div> 