<form action="<?=App::config('url')?>predavac/akcija" method="post">

    <fieldset>
        <legend>Detalji predavača</legend>

        <label>
            Ime
            <input type="text" name="ime" value="<?=$predavac->ime?>" />
        </label>

        <!-- ispravnije -->
        <label for="prezime">Prezime</label>
        <input type="text" name="prezime" id="prezime" 
         value="<?=$predavac->prezime?>">

        <label for="email">Email</label>
        <input type="email" name="email" id="email" value="<?=$predavac->email?>">

        <label for="oib">OIB</label>
        <input type="text" name="oib" id="oib" value="<?=$predavac->oib?>">

        <label for="iban">IBAN</label>
        <input type="text" name="iban" id="iban" value="<?=$predavac->iban?>">

        <input type="hidden" name="sifra" value="<?=$predavac->sifra?>">

        <div class="grid-x grid-padding-x">
            <div class="large-4 cell">
                <a  class="alert button expanded" 
                href="<?=App::config('url')?>predavac/index">Odustani</a>
            </div>
            <div class="large-8 cell">
                <input type="submit" class="success button expanded" value="<?=$akcija?>">
            </div>
        </div>
        <?=$poruka?>

    </fieldset>
</form> 