<div class="grid-x grid-padding-x">
    <?php include 'dodajNovi.phtml';?>
    <?php foreach($predavaci as $predavac): ?>
        <div class="large-3 medium-4 cell">
            <div class="callout"  style="text-align: center; min-height: 220px;">
            <h1 style="font-size: 1.5rem;">
            <?=$predavac->ime?> <?=$predavac->prezime?></h1>
            <hr />
            <?=$predavac->email?>
            <hr />
            <a href="<?=App::config('url')?>predavac/detalji/<?=$predavac->sifra?>">
                    <i title="Promjeni" 
                        class="fas fa-2x fa-edit"></i>
                </a>   
                <?php if($predavac->grupa==0): ?>
                    <a onclick="return confirm('Sigurno obrisati?');" style="margin-left: 20px;" href="<?=App::config('url')?>predavac/brisanje/<?=$predavac->sifra?>">
                        <i style="color: red" title="Obriši " 
                            class="fas fa-2x fa-trash"></i>
                    </a>  
                <?php else:?>
                    <i style="margin-left: 20px;color: gray" 
                    title="Ne može se obrisati jer predaje na grupi" 
                            class="fas fa-2x fa-trash"></i>
                <?php endif;?>
            </div>

        </div>
    <?php endforeach;?>
    <?php include 'dodajNovi.phtml';?>
</div> 